### PR TITLE
Pint regex filter

### PR DESCRIPTION
**Pull request by jgleissner**
Support for regex and inverse substring matches.

### CODE REVIEW

**Comment by bear454** [comment]
:+1: It's great to see some useful extension of the the filters!

**Comment by bear454** [comment]
One thing @jgleissner: you'll need to bump the minor version as well, according to semantic versioning.

**Comment by rjschwei** [comment]
Agreed lets bump the version, then file a bug against SLE and get a new package released. We shouldn't hold onto this change in the code only. Also rebuild the package in OBS.

**Comment by jgleissner** [comment]
Sorry, wasn't aware of that. Version bumped. I'll merge and update the packages.

**Pull request merged**
