### PR TITLE
Use exec builtin to source version number from file.

### PR DESCRIPTION
**Pull request by smarlowucf**
From #126, cleanup flake8 error in version import.

### CODE REVIEW

**Comment by rjschwei** [comment]
And this is better why?

No, flake8 complains is not the proper answer

**Comment by bear454** [comment]
I asked @smarlowucf to submit this suggestion as a separate PR... it is better, if we're using flake8, to have a clean flake8 report... so is there some _problem_ with this approach @rjschwei ?

**Comment by smarlowucf** [comment]
Explicit execution on module rather than implicit import relying on a modified python path.

May not be likely but the python path could theoretically change between modifying it and running import. 

```
sys.path.insert(0, mod_path)
# Something manages to change python path
import version
```

The downfall to a module execution is it will always be executed. Granted this module is negligible with one string.

**Comment by smarlowucf** [comment]
Another option would be to use bumpversion to manage the version in multiple places. Moving the logic outside of the setup file.

**Comment by bear454** [comment]
:+1: for moving to `bumpversion`

**Comment by rjschwei** [comment]
OK, I get the argument about not getting used to warnings, fair enough. But why is there a tendency to find the complicated solution?

import lib.susepubliccloudinfoclient.version
from lib.susepubliccloudinfoclient.version import *

yes it is a relative import, but it is in setup.py and not part of the code. So we can appease flake8 and still keep things simple.

**Comment by rjschwei** [comment]
OK, so we are not going to do this!

exec => means as an attacker I can slip whatever code I want into the version file and then have it executed as root during package installation, same holds true for "import" of course. We should move to a "read and extract" method without having any potential code in the version file executed.

**Pull request closed without merging**
