### PR TITLE
[Review] Request from 'schaefi' @ 'SUSE/Enceladus/azureMeta'

### PR DESCRIPTION
**Pull request by schaefi**
Please review the following changes:
- f762876 Added support for internal/external ip discovery
- 16bd5e5 - azuremetadata   + Make the code public   + Rename executable and package to azuremetadata

### CODE REVIEW

**Comment by schaefi** [comment]
@rjschwei, @bear454  added external and internal ip discovery, maybe you and/or James can review

**Comment by rjschwei** [comment]
Looks good to me with the exception of the AzureAgent file name. While the Agent provides the file I don't think we want to tie ourselves to this by name. Lets use functional names. You used AzureDisk as an indication that this contains operations that get data from the Disk, lets use AzureNetwork to indicate the functionality this module provides is related to the network.

**Comment by schaefi** [comment]
yes, makes sense will change it

**Comment by rjschwei** [comment]
Looks like a re-base is required.

**Comment by schaefi** [comment]
merging now before somebody else pushes changes to the old code

**Pull request merged**
