### PR TITLE
Get regions based on account partition.

### PR DESCRIPTION
**Pull request by smarlowucf**
Regions will return based on the account partition. This could be aws, aws-cn or aws-us-gov.

### CODE REVIEW

**Comment by rjschwei** [comment]
I think I know what you are after but this does not have the desired effect. When creating a session with credentials valid for China:

>>> import boto3
>>> session = boto3.session.Session(aws_access_key_id=access_key,aws_secret_access_key=secret_key)
>>> client = session.client('sts')
>>> partition = client.get_caller_identity()['Arn'].split(':')[1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the GetCallerIdentity operation: The security token included in the request is invalid.

Anyway, this would obviously break all the tools.

**Review by rjschwei — CHANGES_REQUESTED** [review]
I'll leave it to you if you want to dig into the issue with China or scrap this and handle the issue at the next level up. Given that China has only 2 regions at this point this is still easy to handle in other ways.

**Comment by rjschwei** [comment]
Last but not least not e that the API is unreliable, I have pointed that out to AWS previously but didn't have a good reproducer. With eu-west-3 only I can now also show that eu-west-3 is missing in an AWS instance in EC2. I have pointed the problem out to AWS, but we might want to rethink this in a different way, which would probably include using the config file somehow.

**Comment by rjschwei** [comment]
And one more thing, the access of the partition when authenticated to gov-cloud also fails.

**Comment by smarlowucf** [comment]
> And one more thing, the access of the partition when authenticated to gov-cloud also fails.

Ah yes, I had this working for both when testing but I realize the issue. If a specific profile or region is not passed in it's pulling the region from default profile. Thus it's trying to authenticate against a connected region. Will see if there's a way around this...

**Comment by smarlowucf** [comment]
> I'll leave it to you if you want to dig into the issue with China or scrap this and handle the issue at the next level up. Given that China has only 2 regions at this point this is still easy to handle in other ways.

I have similar code the next level up but figured it would be helpful here as well. Will see if there's a possible workaround for default profile...

**Comment by smarlowucf** [comment]
>Last but not least not e that the API is unreliable, I have pointed that out to AWS previously but didn't have a good reproducer. With eu-west-3 only I can now also show that eu-west-3 is missing in an AWS instance in EC2.

Had the same issue with the new China region, the problem was the version of botocore. The regions are [hardcoded](https://github.com/boto/botocore/blob/f68c0d0e386b585267a173a89268e7338b45151a/botocore/data/endpoints.json) thus every new region requires a new release of the package.

**Comment by rjschwei** [comment]
Good find on the regions and here I was under the impression that there was finally an API, we had the problem with update python-boto for every new region, I guess that just shifted to botocore. I want to go throw up now.

**Comment by smarlowucf** [comment]
> I want to go throw up now.

😃 It's already json why can't it just be provided by an API?

Anyway, closing this for now. I think the best fix would require a bit of refactoring in publish and deprecate scripts to handle aws profiles and/or another region arg.

We could also pull the region info directly from json which would remove the issue of package version. But this really should be part of the AWS API that boto relies on...

Will note to look into this further.

**Pull request closed without merging**
